%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Matlab\Numerical Model v4\Plots\Convergence\ConvergeData.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 03-Apr-2020 13:29:50

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D6";

% Specify column names and types
opts.VariableNames = ["Nodes", "FailureCycle", "ChangeinCycles", "PercentChange"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
ConvergeData = readtable("D:\Matlab\Numerical Model v4\Plots\Convergence\ConvergeData.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts