%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Matlab\Numerical Model v4\Plots\Inlet Temp Variance\DamageData.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 01-Apr-2020 15:51:43

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D119";

% Specify column names and types
opts.VariableNames = ["Cycle", "T_in_95C", "T_in_97C", "T_in_99C"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
DamageData = readtable("D:\Matlab\Numerical Model v4\Plots\Inlet Temp Variance\DamageData.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts